export const ONLOAD_SEARCH = 'SEARCH_ONLOAD';

export const SUCCESS_SEARCH = 'SEARCH_SUCCESS';

export const NULL_SEARCH = 'SEARCH_NULL';

export const NOT_RESULT_SEARCH = 'SEARCH_NOT_RESULT';

export const FAVOURITES_CHECK = 'FAVOURITES_CHECK';

export const ADD_FAVOURITE_VACANCY = 'FAVOURITES_ADD_VACANCY';

export const DEL_FAVOURITE_VACANCY = 'FAVOURITE_DEL_VACANCY';
