export const ONLOAD_SEARCH = 'SEARCH/ONLOAD';

export const SUCCESS_SEARCH = 'SEARCH/SUCCESS';

export const NULL_SEARCH = 'SEARCH/NULL';

export const NOT_RESULT_SEARCH = 'SEARCH/NOT_RESULT';

export const FAVOURITES_CHECK = 'FAVOURITES_CHECK';

export const ADD_FAVOURITE_VACANCY = 'FAVOURITES/ADD_VACANCY';

export const DEL_FAVOURITE_VACANCY = 'FAVOURITE/DEL_VACANCY';
