export const HANDLE_CHANGE_SEARCH = 'SEARCH/HANDLE_CHANGE';

export const SUCCESS_SEARCH = 'SEARCH/SUCCESS';

export const FAVOURITES_CHECK = 'FAVOURITES_CHECK';

export const ADD_FAVOURITE_VACANCY = 'FAVOURITES/ADD_VACANCY';

export const DEL_FAVOURITE_VACANCY = 'FAVOURITE/DEL_VACANCY';
